FROM python:3.9-slim-buster
RUN apt-get update && \
    apt-get -y install gcc libmariadb-dev
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt