# Generated by Django 3.2.5 on 2021-12-12 15:16

import account.models.account_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_verified', models.BooleanField(blank=True, default=False)),
                ('username', models.TextField(max_length=32)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this superuser site.', verbose_name='staff status')),
                ('is_deleted', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', account.models.account_user.AccountUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('is_can_open_admin', models.BooleanField(blank=True, default=False)),
                ('is_can_buy', models.BooleanField(blank=True, default=False)),
                ('is_can_sell', models.BooleanField(blank=True, default=False)),
                ('is_can_create_account_permission', models.BooleanField(blank=True, default=False)),
                ('is_can_delete_account_permission', models.BooleanField(blank=True, default=False)),
                ('is_can_delete_account', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name_reading', models.CharField(max_length=30)),
                ('middle_name_reading', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name_reading', models.CharField(max_length=30)),
                ('accept_newsletter', models.BooleanField(blank=True, default=False, null=True)),
                ('money', models.PositiveIntegerField(blank=True, default=0)),
                ('all_paid', models.PositiveIntegerField(blank=True, default=0)),
                ('tel', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('address_level_1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('address_level_2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('address_line_1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('address_line_2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='account_permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
