version: '3'

services:
  web:
    container_name: django
    build: ./docker/django_docker
    command:
      python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"

  front:
    container_name: nuxt
    build: ./docker/nuxt_docker
    tty: true
    volumes:
      - ./frontend:/code
    ports:
      - "3000:3000"