version: '3'

services:
  db:
    container_name: vantan_store_db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: vantan_store_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      TZ: "Asia/Tokyo"
    volumes:
      - ./Docker/sql/mysql:/var/lib/mysql
      - ./Docker/sql/sql:/docker-entrypoint-initdb.d
      - ./Docker/sql/sqlcnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  api:
    container_name: vantan_store_api
    build: ./Docker/python
    command: uwsgi --socket :8000 --http :8001  --module config.wsgi --py-autoreload 1 -b 32768
    volumes:
      - ./api/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
      container_name: vantan_store_web
      build: ./Docker/nuxt
      command: >
        bash -c "yarn install &&
        yarn dev"

      ports:
        - 3000:3000
      volumes:
        - ./web/:/app
        - ./web/node_modules:/usr/src/app/node_modules
      tty: true
      working_dir: /app
  
  nginx:
    image: nginx:1.13
    container_name: vantan_store_nginx
    ports:
      - "80:80"
    volumes:
      - ./Docker/nginx/conf:/etc/nginx/conf.d
      - ./Docker/nginx/uwsgi_params:/etc/nginx/uwsgi_params
    depends_on:
      - api
