version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: make env file
          command: |
            echo DEBUG=${DEBUG} > api/.env
            echo SECRET_KEY=${SECRET_KEY} >> api/.env
            echo ALLOWED_HOSTS=${ALLOWED_HOSTS} >> api/.env
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: docker ps
          command: docker ps
